name: CI/CD for Flutter

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.1'

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze and test
        run: flutter analyze && flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Build appBundle
        run: flutter build appbundle

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

      - name: Upload Artifacts TO Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: "build/app/outputs/flutter-apk/app-debug.apk"
          credentials: ${{ secrets.CREDENTIALS }}
          parent_folder_id: ${{ secrets.folderId }}

#      - name: Upload to gdrive
#        uses: adityak74/google-drive-upload-git-action@main
#        with:
#          credentials: ${{ secrets.CREDENTIALS }}
#          filename: "app-debug.apk"
#          artifacts: "build/app/outputs/flutter-apk/app-debug.apk"
#          folderId: ${{ secrets.folderId }}
#          name: "app-release.apk" # optional string
#          overwrite: "true" # optional boolean
#      - name: Make Directory Structure
#        run: |
#          mkdir -p w/x/y
#          date +%s > w/x/y/z
#      - name: Mirror Directory Structure
#        uses: adityak74/google-drive-upload-git-action@main
#        with:
#          credentials: ${{ secrets.CREDENTIALS }}
#          filename: w/x/y/z
#          folderId: ${{ secrets.folderId }}
#          overwrite: "true"
#          mirrorDirectoryStructure: "true"


#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}

#      - name: Build APK
#        run: flutter build apk
#
#      - name: Deploy to Firebase
#        run: |
#          npm install -g firebase-tools
#          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
#        env:
#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


#name: "Build & Release"
#on:
#  pull_request:
#    branches:
#      - dev
#      - test
#  push:
#    branches:
#      - dev
#      - test
#jobs:
#  build:
#    name: Build & Release
#    runs-on: windows-latest
#
#    steps:
#        #1
#      - name: Checkout Repository
#        uses: actions/checkout@v3
#
#      #2
#      - name: Set Up Java
#        uses: actions/setup-java@v3.12.0
#        with:
#          distribution: 'oracle'
#          java-version: '17'
#
#      #3
#      - name: Set Up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.16.1'
#          channel: 'stable'
#
#      #4
#      - name: Install Dependencies
#        uses: flutter pub get
#
#      #5
#      - name: Test flutter app
#        run: flutter test
#
#      #6
#      - name: Build APK
#        run: flutter build apk --release
#
#      #7
#      - name: Build appBundle
#        run: flutter build appbundle
#
#      #8
#      - name: Build IPA
#        run:
#          flutter build ipa --no-codesign
#      - name: Compress Archive and IPAs
#        run: |
#          cd build
#          tar -czf ios_build.tar.gz ios
#
#      #9
#      - name: Upload Artifacts
#        uses: action/upload-artifact@v2
#        with:
#          name: Release
#          path: |
#            build/app/outputs/flutter-apk/app-release.apk
#            build/app/outputs/bundle/release/app-release.aab
#            build/ios_build.tar.gz
#
#      #10
#      - name: Create Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios_build.tar.gz"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}
#
#
