name: "Build & Release"
on:
  pull_request:
    branches:
      - dev
      - test
  push:
    branches:
      - dev
      - test
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest

    steps:
        #1
      - name: Checkout Repository
        uses: actions/checkout@v3

      #2
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      #3
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.1'
          channel: 'stable'

      #4
      - name: Install Dependencies
        uses: flutter pub get

      #5
      - name: Test flutter app
        run: flutter test

      #6
      - name: Build APK
        run: flutter build apk --release

      #7
      - name: Build appBundle
        run: flutter build appbundle

      #8
      - name: Build IPA
        run:
          flutter build ipa --no-codesign
      - name: Compress Archive and IPAs
        run: |
          cd build
          tar -czf ios_build.tar.gz ios

      #9
      - name: Upload Artifacts
        uses: action/upload-artifact@v2
        with:
          name: Release
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
            build/ios_build.tar.gz

      #10
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab,build/ios_build.tar.gz"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
            

